export const therapyData = {
  sound: [
    {
      id: 1,
      title: "Calm Ocean Waves",
      src: "/audio/calm-ocean-waves.mp3",
      desc: "Gentle waves for relaxation",
    },
    {
      id: 2,
      title: "Forest Serenity",
      src: "/audio/forest-serenity.mp3",
      desc: "Birds and rustling leaves",
    },
    {
      id: 3,
      title: "Rainfall Bliss",
      src: "/audio/rainfall-bliss.mp3",
      desc: "Soft rain for sleep",
    },
    {
      id: 4,
      title: "Mountain Breeze",
      src: "/audio/mountain-breeze.mp3",
      desc: "Whistling winds",
    },
    {
      id: 5,
      title: "Tibetan Singing Bowls",
      src: "/audio/tibetan-singing-bowls.mp3",
      desc: "Harmonic meditation tones",
    },
    {
      id: 6,
      title: "Gentle Piano Melody",
      src: "/audio/gentle-piano-melody.mp3",
      desc: "Soothing piano notes",
    },
    {
      id: 7,
      title: "White Noise Sleep",
      src: "/audio/white-noise-sleep.mp3",
      desc: "Steady noise for focus",
    },
    {
      id: 8,
      title: "Crackling Fireplace",
      src: "/audio/crackling-fireplace.mp3",
      desc: "Warm fire sounds",
    },
    {
      id: 9,
      title: "Birdsong Dawn",
      src: "/audio/birdsong-dawn.mp3",
      desc: "Morning bird chorus",
    },
    {
      id: 10,
      title: "Thunderstorm Calm",
      src: "/audio/thunderstorm-calm.mp3",
      desc: "Distant thunder and rain",
    },
    {
      id: 11,
      title: "Wind Chimes",
      src: "/audio/wind-chimes.mp3",
      desc: "Gentle chime melodies",
    },
    {
      id: 12,
      title: "River Flow",
      src: "/audio/river-flow.mp3",
      desc: "Steady flowing water",
    },
    {
      id: 13,
      title: "Night Crickets",
      src: "/audio/night-crickets.mp3",
      desc: "Evening cricket symphony",
    },
    {
      id: 14,
      title: "Soft Harp",
      src: "/audio/soft-harp.mp3",
      desc: "Delicate harp strings",
    },
    {
      id: 15,
      title: "Cave Ambience",
      src: "/audio/cave-ambience.mp3",
      desc: "Echoing drips",
    },
    {
      id: 16,
      title: "Autumn Leaves",
      src: "/audio/autumn-leaves.mp3",
      desc: "Rustling fall foliage",
    },
    {
      id: 17,
      title: "Flute Serenity",
      src: "/audio/flute-serenity.mp3",
      desc: "Calm flute notes",
    },
    {
      id: 18,
      title: "Distant Waterfall",
      src: "/audio/distant-waterfall.mp3",
      desc: "Faint cascading water",
    },
    {
      id: 19,
      title: "Zen Bell Sounds",
      src: "/audio/zen-bell-sounds.mp3",
      desc: "Peaceful garden ambience",
    },
    {
      id: 20,
      title: "Crystal Bowls",
      src: "/audio/crystal-bowls.mp3",
      desc: "Resonant healing tones",
    },
    {
      id: 21,
      title: "Lakeside Waves",
      src: "/audio/lakeside-waves.mp3",
      desc: "Gentle lake ripples",
    },
    {
      id: 22,
      title: "Soft Rainfall",
      src: "/audio/soft-rainfall.mp3",
      desc: "Light rain patter",
    },
  ],
  video: [
    {
      id: 1,
      title: "Guided Meditation",
      src: "https://www.youtube.com/embed/ZToicYcHIOU?si=sq2iDdtlSP0xYFIA",
      desc: "10-min mindfulness",
    },
    {
      id: 2,
      title: "Yoga Flow",
      src: "https://www.youtube.com/embed/v7AYKMP6rOE",
      desc: "Energizing stretches",
    },
    {
      id: 3,
      title: "Nature Visualization",
      src: "https://www.youtube.com/embed/KJwYBJMSbPI?si=4IUWy4BN94K8esh-",
      desc: "Calm forest stream",
    },
    {
      id: 4,
      title: "Breathwork Session",
      src: "https://www.youtube.com/embed/VUjiXcfKBn8?si=7kEpsfVB2yP7WIn0",
      desc: "Deep relaxation",
    },
    {
      id: 5,
      title: "Sunset Over Lake",
      src: "https://www.youtube.com/embed/64ef8cnOOHI?si=Jajlxf-Pu2b1lzsU",
      desc: "Peaceful sunset",
    },
    {
      id: 6,
      title: "Starry Night Sky",
      src: "https://www.youtube.com/embed/Bbp1-p2FoXU?si=ut0jkQSUPA1RH8sm",
      desc: "Timelapse of stars",
    },
    {
      id: 7,
      title: "Waterfall Serenity",
      src: "https://www.youtube.com/embed/V1RPi2MYptM?si=2naBueXdofwBMjbV",
      desc: "Cascading waterfall",
    },
    {
      id: 8,
      title: "Forest",
      src: "https://www.youtube.com/embed/RzVvThhjAKw?si=aFTOxAJ0McfmTymS",
      desc: "Birds in treetops",
    },
    {
      id: 9,
      title: "Gentle Rain",
      src: "https://www.youtube.com/embed/CpS5Ex1Wx-4?si=0Nyxhf2uvYfDfp3E",
      desc: "Rain on leaves",
    },
    {
      id: 10,
      title: "Snowfall",
      src: "https://www.youtube.com/embed/vz91QpgUjFc?si=wuKommtbg1F_bov6",
      desc: "Quiet snow falling",
    },
    {
      id: 11,
      title: "Desert Dunes",
      src: "https://www.youtube.com/embed/o9i6ljOdp5A?si=D6IxsC4NtJvCYTx3",
      desc: "Wind over sand",
    },
    {
      id: 12,
      title: "Aurora Borealis",
      src: "https://www.youtube.com/embed/T75IKSXVXlc?si=DqSqa--gtifLt4zE",
      desc: "Northern lights dance",
    },
    {
      id: 13,
      title: "Cloud Timelapse",
      src: "https://www.youtube.com/embed/Qu7mcKZgqv0?si=g0i6boFIpfxH8VO_",
      desc: "Moving clouds",
    },
    {
      id: 14,
      title: "Candle Meditation",
      src: "https://www.youtube.com/embed/4eHsIhb0vZQ?si=E_pAeczOGfja--pI",
      desc: "Flickering flame",
    },
    {
      id: 15,
      title: "Windmill Calm",
      src: "https://www.youtube.com/embed/ueX7B4veLwY?si=pSB2VG2hcw8bmG0B",
      desc: "Spinning windmill",
    },
    {
      id: 16,
      title: "Autumn Forest",
      src: "https://www.youtube.com/embed/TOHYkccYfUk?si=qwS7KZy6_gbFat9h",
      desc: "Falling leaves",
    },
    {
      id: 17,
      title: "Bamboo Grove",
      src: "https://www.youtube.com/embed/mi2Eb3wt74Y?si=r4v7sMp-DpgzSonh",
      desc: "Swaying bamboo",
    },
    {
      id: 18,
      title: "Flower Bloom",
      src: "https://www.youtube.com/embed/FV9a4ro5ecw?si=rhODftWbSzWffRB8",
      desc: "Timelapse bloom",
    },
  ],
  other: [
    {
      id: 1,
      title: "Art Therapy Guide",
      desc: "Express your emotions through creative art",
      tool: "Paints or pencils",
      banner:
        "https://images.unsplash.com/photo-1614556859483-88c323e4aa01?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXJ0JTIwZXhlcmNpc2VzfGVufDB8fDB8fHww",
      steps: [
        "Gather your materials such as paints, pencils, or crayons, ensuring you have everything you need to start your creative journey comfortably and without interruptions.",
        "Find a quiet space where you can focus, free from distractions, allowing your mind to settle and fully engage in the artistic process ahead.",
        "Start by drawing how you feel, letting colors represent your emotions, using bold reds for anger or soft blues for calm to express yourself freely.",
        "Reflect on your artwork for 5 minutes, thinking about what it reveals about your emotions and how the process made you feel overall.",
      ],
      images: [
        "https://images.unsplash.com/photo-1627141565818-db5c30649c0d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFpbnRpbmclMjBtYXRlcmlhbHxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1611248293543-e71973f8b94b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cXVpZXQlMjBwbGFjZSUyMGZvciUyMGFydHxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1505569127510-bde1536937bc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGRyYXdpbmd8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1541680670548-88e8cd23c0f4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YXJ0d29ya3xlbnwwfHwwfHx8MA%3D%3D",
      ],
    },
    {
      id: 2,
      title: "Journaling Prompts",
      desc: "Reflect daily with guided prompts",
      tool: "Notebook",
      banner:
        "https://images.unsplash.com/photo-1550592704-6c76defa9985?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8am91cm5hbGluZ3xlbnwwfHwwfHx8MA%3D%3D",
      steps: [
        "Set aside 10 minutes daily to journal, creating a consistent habit that allows you to process your thoughts and emotions in a structured, reflective way.",
        "Pick a prompt like 'What made me smile today?' to guide your writing, sparking positivity and helping you focus on meaningful moments in your life.",
        "Write freely without editing, letting your thoughts flow naturally onto the page, capturing raw emotions and ideas without worrying about perfection or structure.",
        "Review your entries weekly to notice patterns, reflect on your growth, and gain insights into how your feelings and experiences evolve over time.",
      ],
      images: [
        "https://images.unsplash.com/photo-1483546363825-7ebf25fb7513?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8am91cm5hbHxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d3JpdHRpbmd8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y3JlYXRpdmUlMjB3cml0aW5nfGVufDB8fDB8fHww",
        "https://images.unsplash.com/photo-1630032866155-f87ec4d047bd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGNyZWF0aXZlJTIwd3JpdGluZyUyMHBhdHRlcm4lMjByZXZpZXd8ZW58MHx8MHx8fDA%3D",
      ],
    },
    {
      id: 3,
      title: "Mandala Coloring",
      desc: "Find calm through coloring mandalas",
      tool: "Printable sheets",
      banner:
        "https://images.unsplash.com/photo-1658402995914-22a4ba7e1a94?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bWFuZGFsYSUyMGNvbG9yaW5nfGVufDB8fDB8fHww",
      steps: [
        "Print or draw a mandala design, choosing a pattern that resonates with you and preparing a canvas for a calming and meditative coloring experience.",
        "Choose calming colors like soft blues, greens, or purples, selecting shades that soothe your mind and enhance the relaxation of the coloring process.",
        "Color slowly, focusing on each section, letting your attention dwell on the details as a way to unwind and practice mindfulness with every stroke.",
        "Display your finished mandala in a special place, admiring your work as a reminder of your creativity and the peace it brought you.",
      ],
      images: [
        "https://images.unsplash.com/photo-1590225472433-e20c5d118c60?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG1hbmRhbGElMjBkZXNpZ24lMjBkcmF3aW5nfGVufDB8fDB8fHww",
        "https://images.unsplash.com/photo-1660326447860-a4811bafdc75?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FsbWluZyUyMGNvbG9ycyUyMGZvciUyMGRyYXdpbmd8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1609436792750-d32fab9fe2cb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGRyYXdpbmclMjB3aXRoJTIwZm9jdXN8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1649089473160-91a7b1c466d7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG1hbmRhbGElMjBkcmF3aW5nfGVufDB8fDB8fHww",
      ],
    },
    {
      id: 4,
      title: "Gratitude Exercise",
      desc: "Boost positivity with gratitude",
      tool: "App or paper",
      banner:
        "https://images.unsplash.com/photo-1668027400307-c316968e8015?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JhdGl0dWRlJTIwZXhlcmNpc2V8ZW58MHx8MHx8fDA%3D",
      steps: [
        "List 3 things you're grateful for each day, writing them down to cultivate positivity and shift your focus toward the blessings in your life consistently.",
        "Write why they matter to you, exploring their significance in depth to deepen your appreciation and connect emotionally with each item on your list.",
        "Read your list aloud to yourself, hearing the words to reinforce their meaning and let the gratitude sink in fully as a daily practice.",
        "Repeat for 21 days to build a habit, allowing this routine to transform your mindset and bring a lasting sense of thankfulness and joy.",
      ],
      images: [
        "https://images.unsplash.com/photo-1579600161224-cac5a2971069?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cG9zaXRpdml0eXxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1731963094554-c5c981ccdefd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZmVlbGluZ3MlMjBhYm91dCUyMHdyaXR0aW5nfGVufDB8fDB8fHww",
        "https://images.unsplash.com/photo-1721206061215-9608db522adf?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cmVhZGluZyUyMG9mJTIwc2VsZiUyMHdyaXR0aW5nfGVufDB8fDB8fHww",
        "https://images.unsplash.com/photo-1509528640600-be205362320b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHJlcGVhdCUyMHdyaXR0aW5nJTIwZm9yJTIwaGFiaXR8ZW58MHx8MHx8fDA%3D",
      ],
    },
    {
      id: 5,
      title: "Mindful Breathing",
      desc: "Calm your mind with focused breathing",
      tool: "Quiet space",
      banner:
        "https://images.unsplash.com/photo-1646820431248-e5fb9cda87ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fG1pbmRmdWwlMjBicmVhdGhpbmd8ZW58MHx8MHx8fDA%3D",
      steps: [
        "Sit comfortably in a quiet place where you won’t be disturbed, settling into a position that supports relaxation and helps you focus inward peacefully.",
        "Close your eyes and focus on your breath, tuning out distractions to center your mind and prepare for a calming and restorative breathing exercise.",
        "Inhale deeply for 4 seconds, hold for 4, exhale for 4, repeating this rhythm to regulate your breathing and promote a sense of calm.",
        "Repeat for 5 minutes, maintaining the pattern to fully relax your body and mind, letting stress melt away with each controlled breath cycle.",
      ],
      images: [
        "https://images.unsplash.com/photo-1685175474145-e8cb170c27f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2l0dGluZyUyMGluJTIwcXVpZXQlMjBwbGFjZXxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/reserve/YEc7WB6ASDydBTw6GDlF_antalya-beach-lulu.jpg?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWVkaXRhdGlvbnxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGltZXxlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bWVkaXRhdGlvbnxlbnwwfHwwfHx8MA%3D%3D",
      ],
    },
    {
      id: 6,
      title: "Nature Walk",
      desc: "Recharge with a mindful walk in nature",
      tool: "Outdoor space",
      banner:
        "https://images.unsplash.com/uploads/1412533519888a485b488/bb9f9777?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bmF0dXJlJTIwd2Fsa3xlbnwwfHwwfHx8MA%3D%3D",
      steps: [
        "Find a nearby park or natural area where you can immerse yourself in greenery, choosing a spot that feels inviting and peaceful for your walk.",
        "Walk slowly, noticing sights and sounds around you, taking time to appreciate the rustling leaves, birdsong, and beauty of nature as you go.",
        "Take 5 deep breaths of fresh air, inhaling deeply to fill your lungs, feeling refreshed and connected to the outdoors with each breath you take.",
        "Spend at least 20 minutes in nature, allowing the time to unwind, recharge, and enjoy the calming effects of being surrounded by the natural world.",
      ],
      images: [
        "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGFya3xlbnwwfHwwfHx8MA%3D%3D",
        "https://images.unsplash.com/photo-1604769688135-f245c9f9a486?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHdhbGt8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1688589564655-77c19e47d7c5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTZ8fGElMjBwZXJzb24lMjBicmVhdGhpbmclMjBkZWVwbHklMjBpbiUyMHBhcmt8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1529718836725-f449d3a52881?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2l0dGluZyUyMGluJTIwbmF0dXJlfGVufDB8fDB8fHww",
      ],
    },
  ],
};
